# Generated by Django 6.0.2 on 2026-02-26 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=12)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('meta ads', 'Meta Ads'), ('google ads', 'Google Ads'), ('manual', 'Manual'), ('website', 'Website'), ('referral', 'Referral')], max_length=45)),
                ('status', models.CharField(choices=[('new', 'New'), ('not received', 'Not Received'), ('busy', 'Busy'), ('in progress', 'In Progress'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=45)),
                ('score', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='Leads_lead_status_238935_idx'), models.Index(fields=['source'], name='Leads_lead_source_8bae17_idx'), models.Index(fields=['created_at'], name='Leads_lead_created_726e90_idx')],
            },
        ),
    ]
