# Generated by Django 6.0.2 on 2026-04-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancellled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=25),
        ),
    ]
