# Generated by Django 6.0.2 on 2026-04-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
    ]
