# Generated by Django 6.0.2 on 2026-04-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0009_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('not received', 'Not Received'), ('busy', 'Busy'), ('in progress', 'In Progress'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('converted', 'Converted'), ('lost', 'Lost'), ('spam', 'Spam')], max_length=45),
        ),
    ]
