# Generated by Django 6.0.2 on 2026-05-03 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
        ('Leads', '0010_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ad_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ads.adform'),
        ),
        migrations.AddField(
            model_name='lead',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ads.business'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_platform',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
