# Generated by Django 6.0.2 on 2026-05-11 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
        ('Leads', '0012_lead_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meta_lead_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ad_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='Ads.adform'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='Ads.business'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('meta ads', 'Meta Ads'), ('google ads', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual'), ('website', 'Website'), ('referral', 'Referral')], max_length=45),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('not received', 'Not Received'), ('busy', 'Busy'), ('in progress', 'In Progress'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('converted', 'Converted'), ('lost', 'Lost'), ('spam', 'Spam')], default='new', max_length=45),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['business', 'status'], name='Leads_lead_busines_65a1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['business', 'created_at'], name='Leads_lead_busines_597a91_idx'),
        ),
    ]
