# Generated by Django 6.0.2 on 2026-05-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0013_lead_meta_lead_id_alter_lead_ad_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
