# Generated by Django 6.0.7 on 2026-08-17 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ads', '0002_alter_adaccount_access_token_alter_adform_form_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('custom', 'Custom')], default='starter', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('price_per_user', models.DecimalField(decimal_places=2, default=499.0, max_digits=10)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_start', models.DateField(default=django.utils.timezone.now)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='Ads.business')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('activated', 'Activated'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('plan_changed', 'Plan Changed'), ('price_changed', 'Price Changed'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Billings.subscription')),
            ],
        ),
    ]
