# Generated by Django 6.0.2 on 2026-05-12 08:34

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccount',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='adform',
            name='form_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('onboarded_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding_notes', models.TextField(blank=True)),
                ('owner_name', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('owner_email', encrypted_model_fields.fields.EncryptedEmailField(blank=True)),
                ('owner_phone', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('address', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('gst_number', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('pan_number', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('bank_name', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('bank_account_number', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('bank_ifsc', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('contract_notes', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('internal_remarks', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Ads.business')),
            ],
        ),
    ]
