# Generated by Django 6.0.7 on 2026-09-24 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('excerpt', models.CharField(blank=True, help_text='Short summary shown in listings. Auto-filled from content if left blank.', max_length=300)),
                ('content', models.TextField(help_text='Rich text HTML from Tiptap editor')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/featured/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Required for SEO/accessibility if an image is set', max_length=200)),
                ('meta_title', models.CharField(blank=True, help_text='Defaults to post title if left blank. Keep under 60 chars.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Defaults to excerpt if left blank. Keep under 160 chars.', max_length=160)),
                ('canonical_url', models.URLField(blank=True, help_text='Only set if this content is syndicated elsewhere')),
                ('noindex', models.BooleanField(default=False, help_text='Hide this post from search engines')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='Blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='Blog.tag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='Blog_blogpo_slug_ee953a_idx'), models.Index(fields=['status', 'published_at'], name='Blog_blogpo_status_d6f147_idx')],
            },
        ),
    ]
